import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyDDWZULdUu_7x6PG8ggSWiODMKeHK0ddj8",authDomain:"sos-game-78831.firebaseapp.com",projectId:"sos-game-78831",storageBucket:"sos-game-78831.firebasestorage.app",messagingSenderId:"131969888495",appId:"1:131969888495:web:114dfb000736969e71eb1a",measurementId:"G-KKS99RC8BL"};
const app=initializeApp(firebaseConfig),db=getFirestore(app),$=id=>document.getElementById(id),params=new URLSearchParams(location.search);
let state={screen:params.get("room")?"game":"setup",mode:"ai",maxPlayers:2,boardSize:10,board:[],currentPlayer:"P1",myPlayer:null,scores:{P1:0,P2:0,P3:0,P4:0},players:{},selectedLetter:"S",message:"Choose S or O, then click a square.",roomId:params.get("room")||"",winningCells:[],error:"",unsubscribe:null};
function uid(){let id=localStorage.getItem("sosDeviceId");if(!id){id=Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem("sosDeviceId",id)}return id}
function makeRoomId(){return Math.random().toString(36).slice(2,8)}
function createBoard(size){return Array(size*size).fill("")}
function idx(r,c,s){return r*s+c}function inBounds(r,c,s){return r>=0&&r<s&&c>=0&&c<s}function getCell(b,r,c,s){return b[idx(r,c,s)]||""}function setCell(b,r,c,s,v){b[idx(r,c,s)]=v}
const DIRECTIONS=[[0,1],[1,0],[1,1],[1,-1]];
function countSOSFromMove(board,row,col,size){let count=0,cells=[];for(const[dr,dc]of DIRECTIONS){for(let off=-2;off<=0;off++){let word="",line=[];for(let i=0;i<3;i++){const r=row+(off+i)*dr,c=col+(off+i)*dc;if(!inBounds(r,c,size)){word="";break}word+=getCell(board,r,c,size);line.push(idx(r,c,size))}if(word==="SOS"){count++;cells.push(...line)}}}return{count,cells}}
function isFull(b){return b.every(Boolean)}function nextPlayer(cur,max){const n=Number(cur.slice(1));return"P"+((n%max)+1)}
function playerLabel(p){if(!p)return"";if(state.mode==="ai"&&p==="P2")return"Computer";return"Player "+p.slice(1)}
function findAIMove(board,size){const empty=[];let best=null;for(let r=0;r<size;r++){for(let c=0;c<size;c++){if(getCell(board,r,c,size))continue;empty.push([r,c]);for(const letter of["S","O"]){const test=board.slice();setCell(test,r,c,size,letter);const score=countSOSFromMove(test,r,c,size).count;if(score>0&&(!best||score>best.score))best={row:r,col:c,letter,score}}}}if(best)return best;for(const[r,c]of empty){for(const letter of["S","O"]){const test=board.slice();setCell(test,r,c,size,letter);if(countSOSFromMove(test,r,c,size).count>0)return{row:r,col:c,letter,score:0}}}if(!empty.length)return null;const[row,col]=empty[Math.floor(Math.random()*empty.length)];return{row,col,letter:Math.random()>.5?"S":"O",score:0}}
function gameToFirebase(s){return{mode:s.mode,maxPlayers:s.maxPlayers,boardSize:s.boardSize,board:s.board,currentPlayer:s.currentPlayer,scores:s.scores,players:s.players,winningCells:s.winningCells,updatedAt:serverTimestamp()}}
function applyFirebaseGame(data){state.mode=data.mode||state.mode;state.maxPlayers=data.maxPlayers||2;state.boardSize=data.boardSize||10;state.board=Array.isArray(data.board)?data.board:createBoard(state.boardSize);state.currentPlayer=data.currentPlayer||"P1";state.scores=data.scores||{P1:0,P2:0,P3:0,P4:0};state.players=data.players||{};state.winningCells=Array.isArray(data.winningCells)?data.winningCells:[];const deviceId=uid();for(const[p,savedId]of Object.entries(state.players)){if(savedId===deviceId)state.myPlayer=p}}
function localNewGame(){state.screen="game";state.roomId="";state.maxPlayers=state.mode==="ai"?2:state.maxPlayers;state.board=createBoard(state.boardSize);state.currentPlayer="P1";state.myPlayer="P1";state.players={P1:uid()};state.scores={P1:0,P2:0,P3:0,P4:0};state.winningCells=[];state.message="Choose S or O, then click a square.";state.error="";render()}
async function createOnlineGame(){try{state.error="";state.mode="online";state.roomId=makeRoomId();state.screen="game";state.currentPlayer="P1";state.myPlayer="P1";state.players={P1:uid()};state.board=createBoard(state.boardSize);state.scores={P1:0,P2:0,P3:0,P4:0};state.winningCells=[];state.message="Online game created. Share the room link.";await setDoc(doc(db,"games",state.roomId),gameToFirebase(state));const url=new URL(location.href);url.searchParams.set("room",state.roomId);history.replaceState(null,"",url.toString());listenToRoom();render()}catch(err){state.error=err.code?`${err.code}: ${err.message}`:String(err);render()}}
async function joinRoom(){try{state.error="";const ref=doc(db,"games",state.roomId),snap=await getDoc(ref);if(!snap.exists()){state.error="This room does not exist.";render();return}applyFirebaseGame(snap.data());const deviceId=uid();let alreadyIn=null;for(const[p,id]of Object.entries(state.players)){if(id===deviceId)alreadyIn=p}if(!alreadyIn){for(let i=1;i<=state.maxPlayers;i++){const p="P"+i;if(!state.players[p]){state.players[p]=deviceId;state.myPlayer=p;break}}}else state.myPlayer=alreadyIn;if(!state.myPlayer){state.error="This game already has the maximum number of players.";render();return}await setDoc(ref,{players:state.players,updatedAt:serverTimestamp()},{merge:true});listenToRoom();render()}catch(err){state.error=err.code?`${err.code}: ${err.message}`:String(err);render()}}
function listenToRoom(){if(!state.roomId)return;if(state.unsubscribe)state.unsubscribe();const ref=doc(db,"games",state.roomId);state.unsubscribe=onSnapshot(ref,snap=>{if(!snap.exists())return;const oldMyPlayer=state.myPlayer;applyFirebaseGame(snap.data());if(oldMyPlayer)state.myPlayer=oldMyPlayer;render()},err=>{state.error=err.code?`${err.code}: ${err.message}`:String(err);render()})}
async function saveOnlineMove(){await setDoc(doc(db,"games",state.roomId),gameToFirebase(state),{merge:true})}
function handleMove(cellIndex){if(state.error&&state.error.includes("maximum"))return;if(state.board[cellIndex])return;if(state.mode==="online"&&state.myPlayer!==state.currentPlayer){state.message="It is not your turn.";render();return}if(state.mode==="ai"&&state.currentPlayer==="P2")return;const row=Math.floor(cellIndex/state.boardSize),col=cellIndex%state.boardSize;state.board[cellIndex]=state.selectedLetter;const result=countSOSFromMove(state.board,row,col,state.boardSize);if(result.count>0){state.scores[state.currentPlayer]=(state.scores[state.currentPlayer]||0)+result.count;state.winningCells=Array.from(new Set([...state.winningCells,...result.cells]));state.message=`${playerLabel(state.currentPlayer)} made SOS and gets another turn.`}else{state.currentPlayer=nextPlayer(state.currentPlayer,state.maxPlayers);state.message=`${playerLabel(state.currentPlayer)}'s turn.`}if(isFull(state.board))state.message="Game over. The board is full.";if(state.mode==="online")saveOnlineMove().catch(err=>{state.error=err.code?`${err.code}: ${err.message}`:String(err);render()});render();if(state.mode==="ai"&&state.currentPlayer==="P2"&&!isFull(state.board))setTimeout(aiTurn,450)}
function aiTurn(){const move=findAIMove(state.board,state.boardSize);if(!move)return;const cellIndex=idx(move.row,move.col,state.boardSize);state.board[cellIndex]=move.letter;const result=countSOSFromMove(state.board,move.row,move.col,state.boardSize);if(result.count>0){state.scores.P2+=result.count;state.winningCells=Array.from(new Set([...state.winningCells,...result.cells]));state.message=`Computer placed ${move.letter}, scored, and gets another turn.`;render();if(!isFull(state.board))setTimeout(aiTurn,450)}else{state.currentPlayer="P1";state.message=`Computer placed ${move.letter}. Player 1's turn.`;render()}}
function copyLink(){const link=state.roomId?`${location.origin}${location.pathname}?room=${state.roomId}`:location.href;navigator.clipboard?.writeText(link).then(()=>{state.message="Link copied.";render()})}
function renderSetup(){document.getElementById("app").innerHTML=`<div class="page"><div class="card"><h1>SOS Game</h1><p class="muted">Choose how you want to play.</p><div class="setup-grid"><div class="full"><label><b>Game mode</b></label><select id="setupMode"><option value="ai">Play with AI / computer</option><option value="local">Play on same device</option><option value="online">Play online with shared link</option></select></div><div><label><b>Board size</b></label><input id="setupSize" type="number" min="3" max="40" value="${state.boardSize}"></div><div><label><b>Players</b></label><select id="setupPlayers"><option value="2">2 players</option><option value="3">3 players</option><option value="4">4 players</option></select></div><div class="full actions"><button id="startLocal" class="primary">Start game</button><button id="startOnline">Create online game link</button></div></div>${state.error?`<div class="error">${state.error}</div>`:""}</div></div>`;$('setupMode').value=state.mode;$('setupPlayers').value=String(state.maxPlayers);$('setupMode').onchange=e=>{state.mode=e.target.value};$('setupSize').oninput=e=>{state.boardSize=Math.min(40,Math.max(3,Number(e.target.value)||10))};$('setupPlayers').onchange=e=>{state.maxPlayers=Number(e.target.value)};$('startLocal').onclick=()=>{state.boardSize=Math.min(40,Math.max(3,Number($('setupSize').value)||10));state.maxPlayers=state.mode==="ai"?2:Number($('setupPlayers').value);state.mode==="online"?createOnlineGame():localNewGame()};$('startOnline').onclick=()=>{state.mode="online";state.boardSize=Math.min(40,Math.max(3,Number($('setupSize').value)||10));state.maxPlayers=Number($('setupPlayers').value);createOnlineGame()}}
function renderGame(){const link=state.roomId?`${location.origin}${location.pathname}?room=${state.roomId}`:"";const cells=state.board.map((v,i)=>`<button class="cell ${state.winningCells.includes(i)?"win":""} ${v==="S"?"s-letter":""} ${v==="O"?"o-letter":""}" data-cell="${i}" ${v?"disabled":""}>${v}</button>`).join("");const playerStats=Array.from({length:state.maxPlayers},(_,i)=>{const p="P"+(i+1);return`<div class="stat"><span>${playerLabel(p)}</span><b>${state.scores[p]||0}</b></div>`}).join("");$('app').innerHTML=`<div class="page"><div class="card top"><div><h1>SOS</h1><p class="muted">${state.mode==="online"?`You are ${playerLabel(state.myPlayer)}.`:"Play SOS."}</p></div><div class="actions"><button id="letterS" class="${state.selectedLetter==="S"?"active":""}">S</button><button id="letterO" class="${state.selectedLetter==="O"?"active":""}">O</button>${state.roomId?`<button id="copyBtn">Copy link</button>`:""}<button id="newBtn">New game</button></div></div><div class="game-layout"><div class="card"><h2>Game</h2><div class="message">${state.message}</div><div class="stats"><div class="stat"><span>Turn</span><b>${playerLabel(state.currentPlayer)}</b></div>${playerStats}</div>${link?`<div class="room-link"><b>Room link</b><br>${link}</div>`:""}${state.error?`<div class="error">${state.error}</div>`:""}</div><div class="card"><div class="top"><h2>Board: ${state.boardSize} × ${state.boardSize}</h2><p class="muted">${state.mode==="online"?`This device: ${playerLabel(state.myPlayer)}`:""}</p></div><div class="board-wrap"><div class="board" style="grid-template-columns:repeat(${state.boardSize},38px)">${cells}</div></div></div></div></div>`;$('letterS').onclick=()=>{state.selectedLetter="S";render()};$('letterO').onclick=()=>{state.selectedLetter="O";render()};$('newBtn').onclick=()=>{if(state.unsubscribe)state.unsubscribe();history.replaceState(null,"",location.pathname);state={...state,screen:"setup",roomId:"",error:"",message:"Choose S or O, then click a square."};render()};if($('copyBtn'))$('copyBtn').onclick=copyLink;document.querySelectorAll('[data-cell]').forEach(btn=>{btn.onclick=()=>handleMove(Number(btn.dataset.cell))})}
function render(){state.screen==="setup"?renderSetup():renderGame()}
if(state.roomId){state.mode="online";state.screen="game";joinRoom()}else render();
